language: node_js
git:
  depth: false
node_js:
  - 14

cache:
  directories:
    - node_modules

if: type = pull_request

jobs:
  include:
    - stage: downlod dependencies
      script: yarn
    - stage: check formatting
      script: yarn format:check
    - stage: execute tests
      script: yarn test
    - stage: build
      script: yarn build:all

deploy:
  provider: script
  script: ./publish-docker-image.sh
  on:
    tags: true
    condition: $TRAVIS_BRANCH =~ ^(main|feature/travis-test)$
