language: node_js
git:
  depth: false
node_js:
  - 14

cache:
  directories:
    - node_modules

if: (type = pull_request) OR (branch = feature/travis-test AND type = push AND tag IS present)

jobs:
  include:
    - stage: downlod dependencies
      script: yarn
    - stage: check formatting
      if: type = pull_request
      script: yarn format:check
    - stage: execute tests
      if: type = pull_request
      script: yarn test
    - stage: build
      if: type = pull_request
      script: yarn build:all

deploy:
  provider: script
  script: ./publish-docker-image.sh
  on:
    tags: true
    condition: branch = feature/travis-test AND type = push AND tag IS present
